### ISSUE TITLE
CacheManager can't initiated anymore during TYPO3 bootstrap

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/cropvariantsbuilder#18]
## Upstream changes

According to https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Deprecation-94979-UsingCacheManagerOrDatabaseConnectionsDuringTYPO3Bootstrap.html?highlight=cachemanager the usage of the CacheManager within TCA/Overrides/sys_file_reference.php isn't possible anymore:

_TYPO3 11 LTS throws deprecations_

_TYPO3 12 already throws an exception:_
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/2861556/165889354-3693d65b-cdb8-4557-b6fb-f13547aa190c.png">

## What to do?

As the whole cropvariantsbuilder config is based on (multiple concatenated) yaml file(s) using a cache is very important (see PR https://github.com/josefglatz/cropvariantsbuilder/pull/13) (thank you @infabo btw).

Is there a way to add caching the right new way?

**Comment by helmutstrasser** [comment]
Have a look at my solution, to obviate the use of the CacheManager by introducing a static variable. #25

**Comment by josefglatz** [comment]
Thank you @helmutstrasser. The fix was merged and used in production without problems  in TYPO3 11 LTS.

The same error appears now in TYPO3 12 LTS. But the problematic now is the LanguageServiceFactory which uses Caching heavily.

We need to get this fixed, to get TYPO3 12 support.

**Comment by josefglatz** [comment]
We discussed the problem in the team:

I decided the removal of the translation location magic. I will update the extension asap

**Comment by josefglatz** [comment]
Problem resolved by also removing the translation magic

**Comment by josefglatz** [comment]
Thanks for your support!
